### ISSUE TITLE
Add an intelligent prompt

### ISSUE THREAD

**Issue by Rabbit0306** [leozdgao/em-doccenter#3]
I think document center can add an intelligent prompt for the tag of markdown editor.
The terrible things we don't want happen is just like this picture below:
![Image of terrible](https://github.com/Rabbit0306/123/blob/master/img/20150721165714.png?raw=true)

**Comment by leozdgao** [comment]
Great opinion, this function will be added at next release

**Comment by leozdgao** [comment]
This functionality has been added. So close the issue
